=== JonZorz/Reto2/lenguajedemarcas/XSDReto.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="0.1" xml:lang="es">
<!-- AÃ±adimos el elemento restaurante-->
<xs:element name="Restaurante">
    <xs:complexType>
        <!-- Es un complextype porque hay varios elementos en el elemento restaurante-->
        <xs:sequence>
            <!-- Utilizamos el sequence para que todas las cosas esten ordenadas-->
            <xs:element name="reservas" maxOccurs="unbounded">
                <!-- Hemos utilizado unbouded para que en el xml no haya limite de reservas-->
                <xs:complexType>
                     <xs:sequence>
                                <xs:element name="nombre" minOccurs="1" maxOccurs="1">
                                     <xs:simpleType>
                                        <!-- Tenemos simpletype ya que al contrario que complextype solo tiene un elemento-->
                                           <xs:restriction base="xs:string">
                                            <!-- El comando xs:string es para decir que nuestro elemento es en texto-->
                                               <xs:whiteSpace value="preserve"/>
                                               <!-- El comando preserve te permite poner un espacio en caso de tener un nombre compuesto-->
                                           </xs:restriction>
                                     </xs:simpleType>
                                </xs:element>
                                <xs:element name="apellido" type="xs:string" minOccurs="1" maxOccurs="1"/>
                                <xs:element name="correoElectronico" minOccurs="1">
                                      <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:pattern value="[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}"/>
                                                <!-- Los valores los cuales salen arriba, son aquellos valores que se permiten-->
                                            </xs:restriction>
                                      </xs:simpleType>
                                </xs:element>
                                <xs:element name="numeroTelefono" minOccurs="1" maxOccurs="1">
                                      <xs:simpleType>
                                            <xs:restriction base="xs:integer">
                                                <!-- xs:integer es para que el elemento se de tipo numerico (entero)-->
                                                <xs:totalDigits value="9"/>
                                                <!-- xs:totalDigits es para marcar cuantos valores tiene que haber como maximo-->
                                            </xs:restriction>
                                       </xs:simpleType>
                                </xs:element>
                                <xs:element name="numeroPersona" minOccurs="1" maxOccurs="1">
                                      <xs:simpleType>
                                            <xs:restriction base="xs:integer">
                                                <xs:maxExclusive value="31"/>
                                            </xs:restriction>
                                      </xs:simpleType>
                                 </xs:element> 
                                 <xs:element name="fecha" minOccurs="1" maxOccurs="1" type="xs:date"/>
                                 <!-- xs:date es para mostrarnos que es una fecha-->
                                 <xs:element name="horaReserva" maxOccurs="1" type="xs:time"/>
                                 <!-- xs:time es para mostrar que es una hora-->
                                               
                        </xs:sequence>
                        <xs:attribute name="idReserva" type="idReservaType" use="required"/>
                        <!-- required es para que ese campo sea obligatorio-->
                    </xs:complexType>
                   
                </xs:element>
                
            </xs:sequence>
       </xs:complexType>


</xs:element>

<xs:simpleType name="idReservaType">
                 <xs:restriction base="xs:integer">
                          <xs:totalDigits value="20"/>
                 </xs:restriction>
</xs:simpleType>
                   
            
</xs:schema>

=== JonZorz/Reto2/lenguajedemarcas/RetoXML.xml
<?xml version="1.0" encoding="UTF-8"?>
  <Restaurante  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XSDReto.xsd">
    <!-- Hemos a침adido los usuarios a el xml -->
    
    <reservas idReserva="24">
    
    <nombre>Alejandro</nombre>
    <apellido>Rebollo</apellido>
    <correoElectronico>al.rebollo@aulanz.net</correoElectronico>
    <numeroTelefono>638255599</numeroTelefono>
    <numeroPersona>10</numeroPersona>
    <fecha>2024-05-22</fecha>
    <horaReserva>14:15:00</horaReserva>
    
    </reservas>
   

    <reservas idReserva="25">
    
        <nombre>Maialen</nombre>
        <apellido>Berasategi</apellido>
        <correoElectronico>ma.berasategi@gmail.com</correoElectronico>
        <numeroTelefono>123456789</numeroTelefono>
        <numeroPersona>10</numeroPersona>
        <fecha>2024-05-22</fecha>
        <horaReserva>14:15:00</horaReserva>
        
        </reservas>

        <reservas idReserva="26">
    
            <nombre>Julen</nombre>
            <apellido>Salinas</apellido>
            <correoElectronico>ju.salinas@gmail.com</correoElectronico>
            <numeroTelefono>987654321 </numeroTelefono>
            <numeroPersona>1</numeroPersona>
            <fecha>2024-05-22</fecha>
            <horaReserva>14:15:00</horaReserva>
            
            </reservas>


            <reservas idReserva="27">
    
                <nombre>Pedro</nombre>
                <apellido>De la Rosa</apellido>
                <correoElectronico>pe.delarosa@gmail.com</correoElectronico>
                <numeroTelefono>638456733</numeroTelefono>
                <numeroPersona>6</numeroPersona>
                <fecha>2024-04-24</fecha>
                <horaReserva>20:15:00</horaReserva>
                
                </reservas>


                <reservas idReserva="28">
    
                    <nombre>Markel</nombre>
                    <apellido>Irastorza</apellido>
                    <correoElectronico>ma.irastorza@aulanz.net</correoElectronico>
                    <numeroTelefono>646547776</numeroTelefono>
                    <numeroPersona>3</numeroPersona>
                    <fecha>2024-02-14</fecha>
                    <horaReserva>21:15:00</horaReserva>
                    
                    </reservas>


                    <reservas idReserva="29">
    
                        <nombre>Be침at</nombre>
                        <apellido>Ezkerro</apellido>
                        <correoElectronico>be.ezkerro@aulanz.net</correoElectronico>
                        <numeroTelefono>683551981</numeroTelefono>
                        <numeroPersona>17</numeroPersona>
                        <fecha>2024-04-12</fecha>
                        <horaReserva>13:15:00</horaReserva>
                        
                        </reservas>



                        <reservas idReserva="30">
    
                            <nombre>Cristina</nombre>
                            <apellido>Bayona</apellido>
                            <correoElectronico>cr.bayona@aulanz.net</correoElectronico>
                            <numeroTelefono>692344694</numeroTelefono>
                            <numeroPersona>3</numeroPersona>
                            <fecha>2024-06-15</fecha>
                            <horaReserva>14:30:00</horaReserva>
                            
                            </reservas>



                            <reservas idReserva="31">
    
                                <nombre>Aritz</nombre>
                                <apellido>Larrea</apellido>
                                <correoElectronico>ar.larrea@aulanz.net</correoElectronico>
                                <numeroTelefono>688605774</numeroTelefono>
                                <numeroPersona>29</numeroPersona>
                                <fecha>2024-02-14</fecha>
                                <horaReserva>22:00:00</horaReserva>
                                
                                </reservas>

                                <reservas idReserva="32">
    
                                    <nombre>Markel</nombre>
                                    <apellido>Azpiazu</apellido>
                                    <correoElectronico>ma.azpiazu@aulanz.net</correoElectronico>
                                    <numeroTelefono>638966922</numeroTelefono>
                                    <numeroPersona>23</numeroPersona>
                                    <fecha>2024-07-10</fecha>
                                    <horaReserva>15:00:00</horaReserva>
                                    
                                    </reservas>



                                    <reservas idReserva="33">
    
                                        <nombre>Carmelo</nombre>
                                        <apellido>Ovono</apellido>
                                        <correoElectronico>ca.ovono@aulanz.net</correoElectronico>
                                        <numeroTelefono>683473722</numeroTelefono>
                                        <numeroPersona>2</numeroPersona>
                                        <fecha>2024-02-10</fecha>
                                        <horaReserva>01:00:00</horaReserva>
                                        
                                        </reservas>
                                        <reservas idReserva="34">
    
                                            <nombre>I침aki</nombre>
                                            <apellido>D치vila</apellido>
                                            <correoElectronico>in.davila@aulanz.net</correoElectronico>
                                            <numeroTelefono>672409807</numeroTelefono>
                                            <numeroPersona>10</numeroPersona>
                                            <fecha>2024-02-29</fecha>
                                            <horaReserva>04:00:00</horaReserva>
                                            
                                            </reservas>
</Restaurante>
